title: settings
path: settings

cards:

- type: vertical-stack                    # в отдельный столбец
  cards:

  - type: entities
    show_header_toggle: false
    title: Уведомления о погоде
    entities:
      - entity: input_boolean.scheduled_weather_notification
        name: отправлять уведомления
      
      - type: divider 

  - type: conditional
    conditions:
      - entity: input_boolean.scheduled_weather_notification
        state: "on"
    card:
      type: entities
      entities:
      - entity: input_boolean.scheduled_weather_notification_on_workday_morning
        name: утром в раб день
      - entity: input_boolean.scheduled_weather_notification_on_workday_evening
        name: вечером в раб день
      - entity: input_boolean.scheduled_weather_notification_on_weekend_morning
        name: утром в выходной
      - entity: input_boolean.scheduled_weather_notification_on_weekend_evening
        name: вечером в выходной
      
      - type: divider              

      - entity: input_datetime.weather_choose_time_for_workday_morning
        name: утром в раб день
      - entity: input_datetime.weather_choose_time_for_workday_evening
        name: вечером в раб день
      - entity: input_datetime.weather_choose_time_for_weekend_morning
        name: утром в выходной
      - entity: input_datetime.weather_choose_time_for_weekend_evening
        name: вечером в выходной



- type: vertical-stack                    # в отдельный столбец
  cards:





  - type: entities
    entities:
      - type: custom:bar-card
        positions:
          icon: outside
          indicator: inside
          name: outside
        width: 60%
        height: 15px
        entities:
          - entity: sensor.processor_use
            name: Загрузка CPU
          - entity: sensor.memory_use_percent
            name: Загрузка ОЗУ
          - entity: sensor.disk_use_percent
            name: Диск заполнен
          - entity: sensor.disk_free
            name: Свободное место
            min: 0
            max: 492

  - type: custom:mini-graph-card
    entities:
     - sensor.cpu_temperature
    name: CPU Temperature
    height: 65
    line_width: 2
    font_size: 70
    hours_to_show: 24
    points_per_hour: 2
    show:
     #extrema: true
     fill: true
     #graph: bar
    color_thresholds:
     - value: 60
       color: "#FF0000"
     - value: 40
       color: "#00FF00"

  - type: entities
    show_header_toggle: false
    entities:
      - entity: sensor.universal_socket_voltage
        name: Напряжение
        icon: mdi:home-lightning-bolt-outline

  - type: statistics-graph
    #title: 'Напряжение'
    days_to_show: 7
    chart_type: line
    entities:
      - entity: sensor.universal_socket_voltage
        name: V

- type: vertical-stack                      # в отдельный столбец
  cards:

  - type: custom:browser-player

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:

      - entity: person.id_1
        name: Олег
        #secondary_info: last-changed
        secondary_info: last-updated
        tap_action: none
        hold_action: none

      - type: custom:hui-element
        card_type: history-graph
        entities: [entity: person.id_1]
        hours_to_show: 48
        refresh_interval: 0

      - type: custom:hui-element
        card_type: glance
        show_state: true
        entities:

          - entity: person.id_1
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('person.id_1', 'home') else 'red' }};
                }
            name: GPS
            icon: mdi:google-maps
            tap_action: none
            hold_action: none

        #  - entity: sensor.oleg_mob_wifi_connection
        #    card_mod:
        #      style: |
        #        :host {
        #          --paper-item-icon-color: {{ 'green' if is_state('device_tracker.id_1_mob_wifi, 'home') else 'red' }};
        #        }
        #    name: WiFi
        #    icon: mdi:wifi
        #    tap_action: none
        #    hold_action: none

          - entity: sensor.oleg_mob_battery_level
            name:  Ур заряда
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if (states('sensor.oleg_mob_battery_level')|float > 20) else 'red' }};
                }
            tap_action: none
            hold_action: none


          - entity: input_boolean.button_to_display_the_map
            name:  Карта
            icon: mdi:earth
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('input_boolean.button_to_display_the_map', 'on') else 'red' }};
                }
            #show_state: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.button_to_display_the_map
  - type: conditional
    conditions:
      - entity: input_boolean.button_to_display_the_map
        state: "on"
    card:
      type: entities
      entities:
        - entity: sensor.oleg_mob_geocoded_location
          name: 'Адрес:'
          tap_action: none
          hold_action: none
          secondary_info: last-updated

        - type: custom:hui-element
          card_type: map
          class: map
          dark_mode: true
          aspect_ratio: 16:9
          hours_to_show: 6
          entities: [person.id_1]
          default_zoom: 16


  - type: entities
    state_color: true
    show_header_toggle: false
    entities:

      - entity: person.id_2
        name: Аня
        #secondary_info: last-changed
        secondary_info: last-updated
        tap_action: none
        hold_action: none

      - type: custom:hui-element
        card_type: history-graph
        entities: [entity: person.id_2]
        hours_to_show: 48
        refresh_interval: 0

      - type: custom:hui-element
        card_type: glance
        show_state: true
        entities:

          - entity: person.id_2
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('person.id_2', 'home') else 'red' }};
                }
            name: GPS
            icon: mdi:google-maps
            tap_action: none
            hold_action: none

        #  - entity: sensor.oleg_mob_wifi_connection
        #    card_mod:
        #      style: |
        #        :host {
        #          --paper-item-icon-color: {{ 'green' if is_state('device_tracker.id_1_mob_wifi, 'home') else 'red' }};
        #        }
        #    name: WiFi
        #    icon: mdi:wifi
        #    tap_action: none
        #    hold_action: none

          - entity: sensor.ann_mob_battery_level
            name:  Ур заряда
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if (states('sensor.ann_mob_battery_level')|float > 20) else 'red' }};
                }
            tap_action: none
            hold_action: none


          - entity: input_boolean.button_to_display_the_map
            name:  Карта
            icon: mdi:earth
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('input_boolean.button_to_display_the_map', 'on') else 'red' }};
                }
            #show_state: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.button_to_display_the_map
  - type: conditional
    conditions:
      - entity: input_boolean.button_to_display_the_map
        state: "on"
    card:
      type: entities
      entities:
        - entity: sensor.ann_mob_geocoded_location
          name: 'Адрес:'
          tap_action: none
          hold_action: none
          secondary_info: last-updated

        - type: custom:hui-element
          card_type: map
          class: map
          dark_mode: true
          aspect_ratio: 16:9
          hours_to_show: 6
          entities: [person.id_2]
          default_zoom: 16












#
