title: settings_bathroom
path: settings_bathroom

cards:

- type: vertical-stack                    # в отдельный столбец
  cards:

  - type: entities
    show_header_toggle: false
    title: Вентиляция
    entities:
      - entity: switch.bathroom_fan
        name: Вентиляция
        secondary_info: last-changed
      - type: divider 
      - entity: binary_sensor.bathroom_fan_problem
        name: fan_problem
        secondary_info: last-changed
      - entity: binary_sensor.bathroom_climate_problem
        name: climate_problem
        secondary_info: last-changed
      - entity: input_number.bathroom_fan_on_humidity_above
        name: threshold
        secondary_info: last-changed     
      - type: divider 
      - entity: automation.bathroom_fan_on
        name: включение вентиляции если свет ON (4мин)
        secondary_info: last-updated
      - entity: input_number.bathroom_fan_dnd_start
        name: dnd_start_hour
        secondary_info: last-updated
      - entity: input_number.bathroom_fan_dnd_end
        name: dnd_end_hour
        secondary_info: last-updated
      - entity: automation.bathroom_fan_off
        name: выключение вентиляция если свет OFF и климат OK (30с)
        secondary_info: last-updated
      - entity: automation.bathroom_fan_off_emergency
        name: аварийное выключение вентиляции (1мин)
        secondary_info: last-updated


- type: vertical-stack                    # в отдельный столбец
  cards:

  - type: entities
    show_header_toggle: false
    title: Свет
    entities:
      - entity: light.bathroom_lamp
        name: Свет
        secondary_info: last-changed

      - type: divider 
      - entity: binary_sensor.bathroom_light_problem
        name: light_problem (10мин)
        secondary_info: last-changed
 
      - type: divider 
      - entity: automation.bathroom_light_motion
        name: Вкл/Выкл света от движения
        secondary_info: last-updated
      - entity: input_number.bathroom_delay_before_off_light
        name: delay_before_off_light
        secondary_info: last-updated
      - entity: automation.bathroom_light_off_emergency
        name: аварийное выключение света через 10 мин
        secondary_info: last-updated



- type: vertical-stack                      # в отдельный столбец
  cards:

  - type: custom:browser-player

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:

      - entity: person.id_1
        name: Олег
        #secondary_info: last-changed
        secondary_info: last-updated
        tap_action: none
        hold_action: none

      - type: custom:hui-element
        card_type: history-graph
        entities: [entity: person.id_1]
        hours_to_show: 48
        refresh_interval: 0

      - type: custom:hui-element
        card_type: glance
        show_state: true
        entities:

          - entity: person.id_1
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('person.id_1', 'home') else 'red' }};
                }
            name: GPS
            icon: mdi:google-maps
            tap_action: none
            hold_action: none

        #  - entity: sensor.oleg_mob_wifi_connection
        #    card_mod:
        #      style: |
        #        :host {
        #          --paper-item-icon-color: {{ 'green' if is_state('device_tracker.id_1_mob_wifi, 'home') else 'red' }};
        #        }
        #    name: WiFi
        #    icon: mdi:wifi
        #    tap_action: none
        #    hold_action: none

          - entity: sensor.oleg_mob_battery_level
            name:  Ур заряда
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if (states('sensor.oleg_mob_battery_level')|float > 20) else 'red' }};
                }
            tap_action: none
            hold_action: none


          - entity: input_boolean.button_to_display_the_map
            name:  Карта
            icon: mdi:earth
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('input_boolean.button_to_display_the_map', 'on') else 'red' }};
                }
            #show_state: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.button_to_display_the_map
  - type: conditional
    conditions:
      - entity: input_boolean.button_to_display_the_map
        state: "on"
    card:
      type: entities
      entities:
        - entity: sensor.oleg_mob_geocoded_location
          name: 'Адрес:'
          tap_action: none
          hold_action: none
          secondary_info: last-updated

        - type: custom:hui-element
          card_type: map
          class: map
          dark_mode: true
          aspect_ratio: 16:9
          hours_to_show: 6
          entities: [person.id_1]
          default_zoom: 16


  - type: entities
    state_color: true
    show_header_toggle: false
    entities:

      - entity: person.id_2
        name: Аня
        #secondary_info: last-changed
        secondary_info: last-updated
        tap_action: none
        hold_action: none

      - type: custom:hui-element
        card_type: history-graph
        entities: [entity: person.id_2]
        hours_to_show: 48
        refresh_interval: 0

      - type: custom:hui-element
        card_type: glance
        show_state: true
        entities:

          - entity: person.id_2
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('person.id_2', 'home') else 'red' }};
                }
            name: GPS
            icon: mdi:google-maps
            tap_action: none
            hold_action: none

        #  - entity: sensor.oleg_mob_wifi_connection
        #    card_mod:
        #      style: |
        #        :host {
        #          --paper-item-icon-color: {{ 'green' if is_state('device_tracker.id_1_mob_wifi, 'home') else 'red' }};
        #        }
        #    name: WiFi
        #    icon: mdi:wifi
        #    tap_action: none
        #    hold_action: none

          - entity: sensor.ann_mob_battery_level
            name:  Ур заряда
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if (states('sensor.ann_mob_battery_level')|float > 20) else 'red' }};
                }
            tap_action: none
            hold_action: none


          - entity: input_boolean.button_to_display_the_map
            name:  Карта
            icon: mdi:earth
            card_mod:
              style: |
                :host {
                  --paper-item-icon-color: {{ 'green' if is_state('input_boolean.button_to_display_the_map', 'on') else 'red' }};
                }
            #show_state: false
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.button_to_display_the_map
  - type: conditional
    conditions:
      - entity: input_boolean.button_to_display_the_map
        state: "on"
    card:
      type: entities
      entities:
        - entity: sensor.ann_mob_geocoded_location
          name: 'Адрес:'
          tap_action: none
          hold_action: none
          secondary_info: last-updated

        - type: custom:hui-element
          card_type: map
          class: map
          dark_mode: true
          aspect_ratio: 16:9
          hours_to_show: 6
          entities: [person.id_2]
          default_zoom: 16












#
