


#######################################################
################## Из свитчей в light
#######################################################





#######################################################
################## Группы света
#######################################################
- platform: group
  name: all lights
  entities:
    - light.hall_lamp
    - light.bedroom_lamp_dimmer
    - light.kitchen_lamp
    - light.bathroom_lamp
